import{a as E,S,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="52371243-7a3c347b3b0dd4397f9276a68",R="https://pixabay.com/api/";async function p(r,t=1){try{return(await E.get(R,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(s){throw console.error("API Error:",s),new Error("Failed to fetch images: "+s.message)}}const h=document.querySelector(".gallery"),g=document.querySelector(".load-more"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:c,tags:e,likes:o,views:n,comments:b,downloads:w})=>`
        <li class="gallery-item">
          <a href="${c}">
            <img src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <p>Likes: ${o}</p>
            <p>Views: ${n}</p>
            <p>Comments: ${b}</p>
            <p>Downloads: ${w}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){h.innerHTML=""}function L(){document.querySelector(".loader").classList.add("active")}function d(){document.querySelector(".loader").classList.remove("active")}function v(){g.classList.add("visible")}function f(){g.classList.remove("visible")}const m=document.querySelector(".form"),$=document.querySelector(".load-more");let l="",i=1,u=0;m.addEventListener("submit",async r=>{if(r.preventDefault(),l=m.elements["search-text"].value.trim(),i=1,!l){a.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}B(),f(),L();try{const t=await p(l,i);if(d(),t.hits.length===0){a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=t.totalHits,y(t.hits),t.hits.length===15&&i*15<u?v():i*15>=u&&a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){d(),a.error({title:"Error",message:t.message,position:"topRight"})}});$.addEventListener("click",async()=>{i+=1,L(),f();try{const r=await p(l,i);d(),y(r.hits),M(),i*15>=u?(a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),f()):v()}catch(r){d(),a.error({title:"Error",message:r.message,position:"topRight"})}});function M(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
